ruoyi:
  profile: /data/upload

server:
  address: 127.0.0.1
  port: 8080

spring:
  devtools:
    restart:
      enabled: false

logging:
  level:
    com.ruoyi: info
    org.springframework: warn

cdn:
  oss:
    active: true
    bucket: ${OSS_BUCKET:yhfoinone}
    uploadUrl: ${OSS_UPLOAD_URL:oss-cn-beijing.aliyuncs.com}
    downloadUrl: ${OSS_DOWNLOAD_URL:oss-cn-beijing.aliyuncs.com}
    accessKeyId: ${OSS_ACCESS_KEY_ID:}
    accessKeySecret: ${OSS_ACCESS_KEY_SECRET:}
    mainDir: ${OSS_MAIN_DIR:upload/}
    validTime: 3600000
    timeout: 600000
